---
title: "DogBreedTraits"
format: html
editor: visual
---

## Loading Library

```{r}
breed_traits <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_traits.csv')
trait_description <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/trait_description.csv')
breed_rank_all <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-01/breed_rank.csv')

```

```{r}
install.packages("tidymodels")
library(tidymodels)
library(tidyverse)

my_data_splits <- initial_split(breed_traits, prop = 0.5)

exploratory_data <- training(my_data_splits)
test_data <- testing(my_data_splits)
```

```{r}
install.packages("janitor")
names(breed_traits) <- janitor::make_clean_names(names(breed_traits))
```

```{r fig.height=6,eval=FALSE}
breed_traits %>%
  mutate(is_terrier=str_detect(breed, "Terrier"))%>%
  mutate(is_beagle=str_detect(breed, "Beagle"))%>%
  mutate(is_corgi=str_detect(breed, "Corgis"))%>%
  mutate(is_chihuaha=str_detect(breed, "Chihuaha"))%>%
  mutate(is_mine=is_terrier+is_beagle+is_corgi+is_chihuaha)%>%
  filter(is_mine>0)%>%
  ggplot()+
  geom_point(aes(x= good_with_young_children, y = breed))


 
```

```{r}
breed_traits
```

Defining a list of large, medium, small dog breeds

```{r}
breed_traits%>%
  large=c("German Shepherd","Rottweilers","Great Danes","Doberman Pinschers","Bermese Mountain Dogs","Cane Corso","Collie","Mastiffs","Belgian Malinois","Weimaraner",)
  medium=c("Retrievers (Labrador)","Golden Retrievers","Bulldogs","Beagles","Pointers","Australian Shepherds","Boxers","Siberian Huskies","Spaniels (English Springer","Brittany","Border Collie","Vizsla","Basset Hounds",)
  small=c("French Bulldogs","Poodles","Dachshunds","Pembroke Welsh Corgis","Yorkshire Terriers","Cavalier King Charles Spaniels","Miniature Schnauzers","Shih Tzu","Boston Terriers","Pomerians","Havanese","Cane Corso","Shetland Sheepdogs","Pug","Cocker Spaniel","Miniature American Shepherd","Chihuahua","Maltese",)
data%>%
  mutate(size = ifelse(breed%in%large,"large",ifelse(breed%in%medium,"medium","small")))
```
